"""Optional PyTorch-backed probabilistic DeepAR forecaster."""

from __future__ import annotations

import numpy as np
import pandas as pd

from ..base import BaseForecaster

try:
    import torch
    from torch import nn
except ImportError:  # pragma: no cover - exercised only when torch is missing
    torch = None
    nn = None


if nn is not None:

    class _DeepARNet(nn.Module):
        def __init__(self, hidden_size: int, num_layers: int, dropout: float):
            super().__init__()
            self.lstm = nn.LSTM(
                input_size=1,
                hidden_size=hidden_size,
                num_layers=num_layers,
                dropout=dropout if num_layers > 1 else 0.0,
                batch_first=True,
            )
            self.mu_head = nn.Linear(hidden_size, 1)
            self.sigma_head = nn.Linear(hidden_size, 1)
            self.softplus = nn.Softplus()

        def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
            output, _ = self.lstm(x)
            last_h = output[:, -1, :]
            mu = self.mu_head(last_h)
            sigma = self.softplus(self.sigma_head(last_h)) + 1e-4
            return mu, sigma


class DeepARForecaster(BaseForecaster):
    """Probabilistic autoregressive neural forecaster based on DeepAR.

    Wraps a pure PyTorch implementation of the DeepAR architecture
    (Salinas et al., 2019). Requires the optional ``torch`` extra
    (``pip install omnicast[torch]``).

    DeepAR trains an autoregressive recurrent network to predict the parameters
    of a Gaussian distribution (:math:`\\mu_t, \\sigma_t`) by minimizing negative
    log-likelihood.

    Multi-step forecasts are generated by simulating sample paths and feeding
    each predicted point back into the network. Prediction intervals reflect the
    dispersion of these simulated paths.

    Not included in :class:`~omnicast.AutoForecaster`'s default candidate list.
    Pass it explicitly via ``AutoForecaster(models=[...])`` to include it.

    Parameters
    ----------
    lookback : int, default 12
        Number of historical steps used as input context for the recurrent network.
    hidden_size : int, default 32
        Dimensionality of the LSTM hidden state.
    num_layers : int, default 2
        Number of recurrent LSTM layers.
    epochs : int, default 100
        Number of full-batch optimization epochs.
    learning_rate : float, default 1e-2
        Learning rate for the Adam optimizer.
    dropout : float, default 0.1
        Dropout probability applied between recurrent layers if ``num_layers > 1``.
    num_samples : int, default 100
        Number of sample trajectories simulated during prediction.
    seed : int, default 0
        Random seed for model parameters and trajectory generation.

    Examples
    --------
    >>> import pandas as pd
    >>> from omnicast import DeepARForecaster
    >>> y = pd.Series([10.0, 11.2, 12.1, 13.0, 14.5, 15.2, 16.0, 17.1])
    >>> model = DeepARForecaster(lookback=3, hidden_size=8, epochs=30, seed=0).fit(y)
    >>> forecast = model.predict(horizon=2)

    Notes
    -----
    .. list-table:: When to use this model
       :header-rows: 1
       :widths: 25 75

       * - Best for
         - Probabilistic forecasting with predictive distributions on short-to-medium series
       * - Avoid when
         - You need an ultra-lightweight installation, exact analytical intervals,
           or deterministic cross-platform reproducibility
       * - Handles trend
         - Implicitly via sliding-window autoregression
       * - Handles seasonality
         - Implicitly if ``lookback`` covers the seasonal period
       * - Extra dependencies
         - ``torch`` (``pip install omnicast[torch]``)
       * - Min. observations
         - ``lookback + 2``
    """

    def __init__(
        self,
        lookback: int = 12,
        hidden_size: int = 32,
        num_layers: int = 2,
        epochs: int = 100,
        learning_rate: float = 1e-2,
        dropout: float = 0.1,
        num_samples: int = 100,
        seed: int = 0,
    ):
        self.lookback = lookback
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.dropout = dropout
        self.num_samples = num_samples
        self.seed = seed

    def _fit(self, y: pd.Series) -> None:
        if torch is None:
            raise ImportError(
                "DeepARForecaster requires the optional 'torch' dependency; "
                "install with `pip install omnicast[torch]`."
            )
        n = len(y)
        if n < self.lookback + 2:
            raise ValueError(
                f"DeepARForecaster requires at least {self.lookback + 2} observations "
                f"for lookback={self.lookback}"
            )

        torch.manual_seed(self.seed)
        values = y.to_numpy(dtype=float)
        self.mean_ = float(values.mean())
        self.std_ = float(values.std()) or 1.0
        scaled = (values - self.mean_) / self.std_

        windows = np.stack(
            [scaled[i : i + self.lookback] for i in range(n - self.lookback)]
        )
        targets = scaled[self.lookback :]
        x = torch.tensor(windows, dtype=torch.float32).unsqueeze(-1)
        target = torch.tensor(targets, dtype=torch.float32).unsqueeze(-1)

        model = _DeepARNet(self.hidden_size, self.num_layers, self.dropout)
        optimizer = torch.optim.Adam(model.parameters(), lr=self.learning_rate)
        model.train()
        for _ in range(self.epochs):
            optimizer.zero_grad()
            mu, sigma = model(x)
            dist = torch.distributions.Normal(mu, sigma)
            loss = -dist.log_prob(target).mean()
            loss.backward()
            optimizer.step()

        model.eval()
        with torch.no_grad():
            fitted_mu, _ = model(x)
            fitted_scaled = fitted_mu.squeeze(-1).numpy()

        self._model = model
        self._n = n
        self._last_window_ = scaled[-self.lookback :].copy()
        self._fitted_scaled_ = fitted_scaled

    def _fitted_values(self) -> np.ndarray:
        fitted = np.full(self._n, np.nan)
        fitted[self.lookback :] = self._fitted_scaled_ * self.std_ + self.mean_
        return fitted

    def _forecast(self, horizon: int) -> tuple[np.ndarray, np.ndarray]:
        torch.manual_seed(self.seed)
        curr = (
            torch.tensor(self._last_window_, dtype=torch.float32)
            .repeat(self.num_samples, 1)
            .unsqueeze(-1)
        )
        preds = []
        with torch.no_grad():
            for _ in range(horizon):
                mu, sigma = self._model(curr)
                dist = torch.distributions.Normal(mu, sigma)
                sample = dist.sample()
                preds.append(sample)
                curr = torch.cat([curr[:, 1:, :], sample.unsqueeze(-1)], dim=1)

        # paths shape: (num_samples, horizon)
        paths = torch.stack(preds, dim=1).squeeze(-1).numpy()
        unscaled_paths = paths * self.std_ + self.mean_

        mean = np.mean(unscaled_paths, axis=0)
        se = np.std(unscaled_paths, axis=0)
        # Numerical safeguard against degenerate sample variance
        se = np.maximum(se, 1e-4)
        return mean, se
